### ISSUE TITLE
Shadow index link not working

### ISSUE THREAD

**Issue by lucas-johnson** [awesome-spectral-indices/awesome-spectral-indices#11]
Thanks for a great library! Has made my life so much easier.

The link for [SI](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.465.8749&rep=rep1&type=pdf) doesn't work. 

Would be great to be able to cite this index.

**Comment by davemlz** [comment]
Hi @lucas-johnson!

Haha, it is always the same with this article. This is the third time the link stops working. If you want the citation, this is the one:

`Rikimaru, A., Roy, P. S., Miyatake, S., 2002. Tropical forest cover density mapping. Tropical Ecology 43, 39–47.`

I'm looking for a valid link, but with no success.

I'll let you know when I find a valid one! Or if you find one, please let me know :)

Best,

David

**Comment by davemlz** [comment]
The link is operational again! :)
