### ISSUE TITLE
NEW INDEX: DSWI

### ISSUE THREAD

**Issue by remi-braun** [awesome-spectral-indices/awesome-spectral-indices#16]
```python
DSWI=SpectralIndex(
    short_name='DSWI',
    long_name='Disease water stress index',
    formula='(N + G) / (S1 + R)',
    reference='10.1016/j.rse.2004.11.012',
    type='vegetation',
    date_of_addition='2022-10-26',
    contributor="https://github.com/remi-braun"
)
```
See the index database page: https://www.indexdatabase.de/db/i-single.php?id=106

**Comment by davemlz** [comment]
Hi @remi-braun,

The provided reference is not the original article of the index.

Note: In the provided reference the authors reference this paper as the original:

```
Apan, A., Held, A., Phinn, S., & Markley, J. (2004). Detecting sugarcane
orange rust disease using EO-1 Hyperion hyperspectral imagery.
International Journal of Remote Sensing, 25, 489 – 498
```

Please confirm this is the original paper of the index :)

**Comment by remi-braun** [comment]
Oh I don't really looked into the _true_ references, so I would trust them 😅

**Comment by davemlz** [comment]
Hi @remi-braun,

According to the original [paper](https://doi.org/10.1080/01431160310001618031), the index you provided is the number 5 in a series of Disease-Water Stress Indices (DSWI). I added the one you provided and also the other 4 :)

Thank you! :rocket:
