### ISSUE TITLE
NEW INDEX: RDI

### ISSUE THREAD

**Issue by remi-braun** [awesome-spectral-indices/awesome-spectral-indices#18]
```python
RDI=SpectralIndex(
    short_name='RDI',
    long_name='Ratio Drought Index',
    formula='S2 / N',
    reference='https://www.indexdatabase.de/db/i-single.php?id=71',
    type='vegetation',
    date_of_addition='2022-10-26',
    contributor="https://github.com/remi-braun"
)
```
See the index database page: https://www.indexdatabase.de/db/i-single.php?id=71

**Comment by davemlz** [comment]
Hi @remi-braun,

The provided reference is not the original article of the index. Please add the original paper or reference :)

**Comment by remi-braun** [comment]
This seems to be it: 
[Ill, John E. Plnder, and Kenneth W. McLeod. "Indications of relative drought stress in longleaf pine from Thematic Mapper data." Photogrammetric Engineering & Remote Sensing 65.4 (1999): 495-501.](https://www.asprs.org/wp-content/uploads/pers/1999journal/apr/1999_apr_495-501.pdf)

**Comment by davemlz** [comment]
Hi @remi-braun,

The index was added and renamed `DSI: Drought Stress Index` (the paper doesn't name it, but Drought Stress is the focus of it). Additionally, the SWIR band used is SWIR1 (TM B5), so the formula was also changed :)

Thank you!

**Comment by remi-braun** [comment]
OK thanks!
