### ISSUE TITLE
NEW INDEX: MXBI

### ISSUE THREAD

**Issue by remi-braun** [awesome-spectral-indices/awesome-spectral-indices#20]
```python
MXBI=SpectralIndex(
    short_name='MXBI',
    long_name='Maxar Built-up Index',
    formula='(RE1 - A) / (RE1 + A)',
    reference='https://resources.maxar.com/optical-imagery/multispectral-reference-guide',
    type='urban',
    date_of_addition='2022-10-26',
    contributor="https://github.com/remi-braun"
)
```
Maxar Built-up Index: https://resources.maxar.com/optical-imagery/multispectral-reference-guide
Useful for detecting impervious surfaces such as buildings and roads

Note that other Maxar indices exist, but they need a `YELLOW` and a `WATER VAPOUR` band

**Comment by davemlz** [comment]
Hi @remi-braun,

This index already exists as `NHFD: Non-Homogeneous Feature Difference` and was also created for WV. Here is the [paper](https://www.semanticscholar.org/paper/Using-WorldView-2-Vis-NIR-MSI-Imagery-to-Support-Wolf/5e5063ccc4ee76b56b721c866e871d47a77f9fb4).

Please add the other indices you mentioned as new Issues using `Y` as the `Yellow` band :)

**Comment by remi-braun** [comment]
Oh okay, I will check this 🙂

And I will add other index, but for that I may need to have access to the `water vapour` band 😅
