### ISSUE TITLE
NEW INDEX: SBI

### ISSUE THREAD

**Issue by remi-braun** [awesome-spectral-indices/awesome-spectral-indices#22]
```python
SBI=SpectralIndex(
    short_name='SBI',
    long_name='Soil Brightness Index',
    formula='(R**2 + N**2)**0.5',
    reference='hal-03207299',
    type='vegetation',
    date_of_addition='2022-10-26',
    contributor="https://github.com/remi-braun"
)
```
The role of the brightness index is to identify the reflectance of soil and to highlight the vegetal cover of bare areas.
*Bannari et al. 1996; Soufiane Maimouni and Bannari 2011*

**Comment by davemlz** [comment]
Hi @remi-braun,

Could you please add the DOI of the index or the URL of the reference in the `reference` attribute?

Thank you! :)

**Comment by remi-braun** [comment]
Wow after maybe 1 hour, I didn't manage to track it down to a single article...

[This one](https://www.sciencedirect.com/science/article/pii/S2095633920300769) links it to https://doi.org/10.1016/0273-1177(89)90481-X, but I don't see any trace of this index in the paper...

**Comment by davemlz** [comment]
I've found it: [https://doi.org/10.1016/S0034-4257(98)00030-3](https://doi.org/10.1016/S0034-4257(98)00030-3). I will add it soon! (as well as the other indices shown in this paper) ;)

**Comment by remi-braun** [comment]
Thanks a lot!

**Comment by davemlz** [comment]
Done! :)

**Comment by remi-braun** [comment]
Thanks !

However, I don't see any index with RED and NIR 😅

**Comment by davemlz** [comment]
The original paper just uses visible for TM and GREEN+RED for SPOT HRV XS ;)

**Comment by remi-braun** [comment]
Ok I will tune it then :)
