### ISSUE TITLE
QST: When is used N2 rather than N ?

### ISSUE THREAD

**Issue by remi-braun** [awesome-spectral-indices/awesome-spectral-indices#27]
Hello,

I was wondering when the band N2 is used rather than N.
Ideed, for example for `NDREI` the formula is: `(N - RE1) / (N + RE1)` even if the RE1 band is at 20m gsd.
Shouldn't it be more logical to use N2 which is 20m native and has a better spectral resolution ?

(I'm assuming that `N2 == N` for other satellites than Sentinel-2)

**Comment by davemlz** [comment]
Hi @remi-braun,

That depends on the index. `N` represents most broad NIR bands from usual platforms. `N2` would be the closest to the Narrow NIR band from Sentinel-2. So, if an index uses a broad NIR value, better go for `N`, if it is closer to the Sentinel-2 Narrow NIR band (or if it is an index created for this specific band), better go for `N2`. But this is a choice I leave to the user. At the moment the indices that use the `N2` band are: `BAIS2` (specifically created for this band), `SeLI` (Specifically created for this band), `TTVI` (Specifically created for this band), and `SR3` (NIR wavelength is closer to this band).

About the GSD QST: Spatially speaking, it would be easier, yes. Spectrally speaking, that depends on the index. If it were me, I would resample to the output GSD and use `N`.

Cheers!

**Comment by remi-braun** [comment]
Ok thanks for the explanation, I better understand your position 👌
If needed, I will fine tune my indices!
