### ISSUE TITLE
Mapping ASI Bands Standard to STAC EO Common Band Names Standard

### ISSUE THREAD

**Issue by m-mohr** [awesome-spectral-indices/awesome-spectral-indices#30]
The list of expressions https://github.com/awesome-spectral-indices/awesome-spectral-indices#expressions has a couple of "common names" for bands (e.g. RE1, RE2 etc) and their mapping to satellite bands.
What I'm missing is how these wavelength ranges would be for other satellites. So let's say I'd run one of the indices on Planet imagery, how do I know which bands to choose? So I think it would be helpful to define a rough range of wavelengths the bands correspond to, e.g. similar to what STAC does: https://github.com/stac-extensions/eo#common-band-names (actually it would be nice to align these tables, the main issue seems to be the missing inidividual rededge1/2/3 bands in STAC).
This would in the end help to pick the right bands for imagery of satellites that are not listed in the table.

Thoughts?

**Comment by davemlz** [comment]
Hey @m-mohr!

That makes a lot of sense. For now, I have actually for each band a set of attributes describing what are the corresponding bands in usual platforms (see [bands.json](https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/main/output/bands.json)). This includes central wavelength and bandwidth in nm.

So, I can take advantage of this and create a mapping of the ASI standard to the STAC standard! I also see you have an Issue + PR open there (https://github.com/stac-extensions/eo/issues/19) from last year. Any chances they are updating the red edge standard soon? I can do it as they have it right now, but it would be cool to have them separately :)

Still, I'll get it done here and wait for an update there!

**Comment by m-mohr** [comment]
Thanks for the positive response!
I'm trying to get the rededge's updated in STAC, but we were not 100% sure which wavelength ranges would fit for the individual bands. Thanks for pointing at the json file with the wavelengths. The wavelength from S2 are very narrow, but the STAC approach should apply for "most" satellites that may have rededge out there, so looking for broader ranges. Not sure how to proceed there though.

**Comment by davemlz** [comment]
That's a hard question. And even more knowing the bandwidths may change across platforms quite easily. What about taking [Sentinel-3 OLCI](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-3-olci/resolutions/radiometric) ranges?

The mapping would be something like:

- S2 MSI Red Edge 1 (B5) -> S3 OLCI Oa11
- S2 MSI Red Edge 2 (B6) -> S3 OLCI Oa12 (not quite happy about this one tho, maybe two separated ranges is better)
- S2 MSI Red Edge 3 (B7) -> S3 OLCI Oa16

**Comment by davemlz** [comment]
Taking Landsat Next as reference may also be a good idea: https://landsat.gsfc.nasa.gov/satellites/landsat-next/ (However, this may be too premature)

**Comment by remi-braun** [comment]
> This mapping is the same one used by [eo-reader](https://eoreader.readthedocs.io/en/v0.19.1/optical_band_mapping.html)

Thanks thinking about EOReader's mapping ! 😉 
Feel free to correct the mapping, I've made it up according to my needs, but some mapping are really questionable, especially for S3 !

Btw, I would really love a universal way of naming spectral bands as I try to implement STAC in EOReader and I'm tired of linking different nomenclatures 😅

**Comment by davemlz** [comment]
@m-mohr @remi-braun ASI just got a request for a new index (CCI: Chlorophyll Carotenoid Index https://github.com/awesome-spectral-indices/awesome-spectral-indices/issues/32) that requires bands that are not included in the actual ASI standard (Band 11 from MODIS https://github.com/awesome-spectral-indices/awesome-spectral-indices/issues/33). At this point it makes sense to change the standard in ASI to make it narrower than it is (this may also help to the inclusion of more narrower indices). I don't know how this may affect the stac-eo and eo-reader standards in the case we want to have a matching mapping for bands. Do you have any ideas?

**Comment by remi-braun** [comment]
You could use [Planet's terminology](https://earth.esa.int/eogateway/missions/planetscope), i.e. `GREEN_I` band (used also in EOReader) and `GREEN` for MODIS' band 12 ?

I don't think it is useful to map every MODIS or even Sentinel-3 bands as they mostly aren't shared among "classic" sensors.
However, it can be powerful (or convenient) to extend MODIS spectral indices to other satellites by "abusive" mapping, as they still could be meaningful.

**Comment by davemlz** [comment]
I also agree that it's not necessary to map all of the bands. And I really like the simple standard of just going like `G` for Green, `R` for Red, and so on, and I could create as you say `G1` and that would be it. But I'm also thinking that I don't want to go to through the same trouble in the future if there are new indices with new bands :face_with_spiral_eyes:: what if there is a new index that uses a green band that is between `G` and `G1`? In this sense, I like what they're doing at stac-eo using the apprx wavelength as part of the standard naming, but then it would be also a problem for bands with different bandwidths.

**Comment by remi-braun** [comment]
I think this will definitely be a mapping issue, added to a readability one 😅 

**BUT** you could use aliases
- keeping clear and simple bands for usual ones
- create more complicated but more explicit names with bandwidth information for all existing bands that are used in your spectral indices.

➡️ Usual bands could be called with two different names, tyhe complicated ones only useful for dense multispectral (or even - who knows - hyperspectral) sensors

In fact this alone could be a library 😁

**Comment by davemlz** [comment]
@m-mohr I've added a mapping to `common_name` for each band in ASI. For now, all Red Edge bands have the same `common_name`, when https://github.com/stac-extensions/eo/issues/19 is merged I'll change the Red Edge values ;)

@remi-braun You're right. Thanks a lot for the ideas! I'll also add the G1 one and keep the match for `eo-reader`!
