### ISSUE TITLE
NEW INDEX: CCI (MODIS Chlorophyll Carotenoid Index)

### ISSUE THREAD

**Issue by joanvlasschaert** [awesome-spectral-indices/awesome-spectral-indices#32]
```python
CCI=SpectralIndex(
    short_name='CCI',
    long_name='MODIS Chlorophyll Carotenoid Index',
    formula='(B11 - B1) / (B11 + B1)',
    reference='https://lpvs.gsfc.nasa.gov/PDF/LPV_VI2018/Gamon_CEOS_CCI_Presentation_180418.pdf',
    application_domain='vegetation',
    date_of_addition='2023-02-11',
    contributor="[github-user-page](https://github.com/joanvlasschaert"
)
```

**Comment by davemlz** [comment]
Hi @joanvlasschaert,

Thank you very much for contributing to Awesome Spectral Indices!

Before adding the new index, please update the `formula` attribute using the [ASI Standard for paltform bands](https://github.com/awesome-spectral-indices/awesome-spectral-indices#expressions) and the `reference` attribute using the DOI of the original source of the index (it seems to be this one: https://doi.org/10.1073/pnas.1606162113).

If there are no matching bands in the ASI Standard for this index please open another Issue with a feature request for new bands :)

Thank you very much!

Best,

David

**Comment by joanvlassch** [comment]
Added the original reference.
CCI=SpectralIndex(
    short_name='CCI',
    long_name='MODIS Chlorophyll Carotenoid Index',
    formula='(B11 - B1) / (B11 + B1)',
    reference='https://www.pnas.org/doi/full/10.1073/pnas.1606162113',
    application_domain='vegetation',
    date_of_addition='2023-02-11',
    contributor="https://github.com/joanvlasschaert"
)

**Comment by davemlz** [comment]
The index was added and will be available in the next version of ASI!

Thank you very much, @joanvlasschaert!
