### ISSUE TITLE
Add MODIS band 11 to ASI Standard

### ISSUE THREAD

**Issue by joanvlassch** [awesome-spectral-indices/awesome-spectral-indices#33]
There are no matching bands in the ASI Standard for the CCI index so I would like to make a feature request for a new band.
MODIS Band 11 is an ocean band in the range 526nm to 536nm, it is in the visible spectrum, at the start of the green.
https://modis.gsfc.nasa.gov/about/specifications.php

**Comment by davemlz** [comment]
Thank you for the request @joanvlassch!

There is a discussion open for the standard names in STAC-EO and Awesome Spectral Indices, I will post this to check what would be the best solution for the bands standard and I'll keep you updated!

Best,

David

**Comment by davemlz** [comment]
The new band has been added! Thank you, @joanvlassch!
