### ISSUE TITLE
NEW INDEX: EBI (Enhanced Bloom Index)

### ISSUE THREAD

**Issue by geoSanjeeb** [awesome-spectral-indices/awesome-spectral-indices#34]
Please, complete the following information:

```python
short-name-of-index=SpectralIndex(
    short_name='EBI',
    long_name='Enhanced Bloom Index',
    formula='(R + G + B)/(G/B*(R - B - e))',
    reference='[link-to-reference-doi-paper](https://doi.org/10.1016/j.isprsjprs.2019.08.006)',
    application_domain='type-of-index (one of [vegetation, burn, water, snow, kernel])',
    date_of_addition='2023-04-18',
    contributor="[github-user-page](https://github.com/geoSanjeeb)"
)
```

**Comment by davemlz** [comment]
Thank you for your contribution!

The index will be available in the new version of ASI!

**Comment by superneyo** [comment]
Spectral index to improve the extraction of built-up area from WorldView-2 imagery

https://www.spiedigitallibrary.org/journals/journal-of-applied-remote-sensing/volume-15/issue-2/024510/Spectral-index-to-improve-the-extraction-of-built-up-area/10.1117/1.JRS.15.024510.short
