### ISSUE TITLE
Any plans to have a Julia package?

### ISSUE THREAD

**Issue by dpabon** [awesome-spectral-indices/awesome-spectral-indices#37]
Congratulations on the outstanding work!!

I wondered if there are any plans on having this package as a Julia package as well?

Cheers,
Daniel

**Comment by davemlz** [comment]
Hey @dpabon!

Thank you! :D

Actually, yes!!! @MartinuzziFrancesco is working on that ;) the repo is private atm, but keep an eye on https://github.com/awesome-spectral-indices

Best,

David

**Comment by MartinuzziFrancesco** [comment]
I am planning around an end to summer release more or less so yeah, do watch this space for updates!

**Comment by davemlz** [comment]
Closing this issue as [SpectralIndices.jl](https://github.com/awesome-spectral-indices/SpectralIndices.jl) has been released! :partying_face:
