### ISSUE TITLE
Filter indice based on satellites

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [awesome-spectral-indices/awesome-spectral-indices#4]
Hi,
Is there a way to filter out indices that aren't supported by a particular satellite?
For example, red edge-related indices can't be calculated with Landsat and will return error like below.
It would be nice to filter out indices that aren't supported for a predefined list of indices.
Cheers,
Daniel
`
EEException: Collection.first: Error in map(ID=LC09_090079_20211106):
Image.select: Pattern 'NDREI' did not match any bands.
`

**Comment by davemlz** [comment]
Hi @Daniel-Trung-Nguyen,

Are you using `spyndex`, `eemont` or `spectral`?

If you're using `eemont` this is donde automatically, but in `spectral` and `spyndex` the idea is that users do it manually so different products can be used, even user-owned rasters.

If the error is occurring in `eemont`: Could you please paste the code in an Issue of the related package so I can check it? :)

Best,

David

**Comment by Daniel-Trung-Nguyen** [comment]
Hi David,
I am using eemont. Pretty typical code. Example below

```
s2_spectral_indices=['NDVI', 'EVI','OSAVI', 'FCVI', # vegetation indices
                   'RGBVI', # RGB indices
                   'MBI', # modified baresoil index
                   'NDDI','NDREI','PSRI', #N index and plant senescence
                   'NDMI','NMDI','MSI', # moisture
                    ]

collection = 'LANDSAT/LC08/C02/T1_L2'
dataset = (ee.ImageCollection(collection)
                  .filterBounds(roi)
                  .filterDate(dates[0],dates[1])
                  .preprocess()
                  .spectralIndices(s2_spectral_indices)
                 )

```

**Comment by davemlz** [comment]
Hi Daniel,

It works perfectly for me (Please see this [Colab Notebook](https://colab.research.google.com/drive/1WaOx_bD5i-Z1cQMyUwZ0b8452IAWaXx3?usp=sharing)).

All indices except the Red Edge indices are calculated.

**Comment by Daniel-Trung-Nguyen** [comment]
It worked if I tried to load one collection.
When I tried to merge ls collections, it didn't work.
Check out this colab notebook here:
https://colab.research.google.com/drive/1Vt11N27sH3Bgk2qcMBGp_2xHCdbMh8qb?usp=sharing

**Comment by davemlz** [comment]
The problem is that you're extending the band names assuming that all indices are going to be computed, which is not true since Landsat has no Red Edge bands.

You have to take those indices out of the list for Landsat, since they can be computed only for Sentinel-2 in `eemont`.

You can check some of the platforms with the required bands for an index computation with `spyndex`:

```python
import spyndex

spyndex.indices.NDVI.platforms
# ['Sentinel-2',
#  'Landsat-OLI',
#  'Landsat-TM',
#  'Landsat-ETM+',
#  'MODIS',
#  'Planet-Fusion']

spyndex.indices.NDREI.platforms
# ['Sentinel-2']
```

**Comment by Daniel-Trung-Nguyen** [comment]
Yes you are correct. I'll make a list of Red edge indices to filter out the indices as a workaround.
Thanks!

**Comment by davemlz** [comment]
You're welcome!
