### ISSUE TITLE
Ambiguous common names "green" and "red edge"

### ISSUE THREAD

**Issue by szwiep** [awesome-spectral-indices/awesome-spectral-indices#42]
The relationship between common name and short/standard name is not 1-to-1 for the "green" or "rededge" common names. This leads to ambiguity when trying to map common names back to short names (e.g if "green" is passed, does the user mean G or G1?). Was this a purposeful design choice? If not, I think updating the common names to "green1", "rededge1",  "rededge2",  and "rededge3"  for the Green and Red Edges respectively could be a possible solution. 

Let me know what you think. I can make a PR if you agree!

**Comment by davemlz** [comment]
Hi @szwiep!

The common names mapping comes from https://github.com/awesome-spectral-indices/awesome-spectral-indices/issues/30. Here the idea was to use the common names from the [eo stac-extension](https://github.com/stac-extensions/eo), making the indices fully compatible. However, the extension hasn't been updated accoridng to the different red edge bands (see https://github.com/stac-extensions/eo/issues/19 and https://github.com/stac-extensions/eo/pull/22#issuecomment-1416515221). Furthermore, in Awesome Spectral Indices (ASI) we have additional bands too (e.g. G1, as you pointed out)

My suggestion: do not use the common names for now. Use the actual [standard of Awesome Spectral Indices](https://github.com/awesome-spectral-indices/awesome-spectral-indices?tab=readme-ov-file#expressions).

Cheers!

David

**Comment by szwiep** [comment]
Thanks for the explanation @davemlz! This makes more sense to me now. I appreciate the response and am excited to see the built-in compatibility with the eo-stac extension.
