### ISSUE TITLE
Remove `common_names` from bands

### ISSUE THREAD

**Issue by davemlz** [awesome-spectral-indices/awesome-spectral-indices#43]
Remove the `common_names` att from bands as it is causing ambiguity. Wait until [eo](https://github.com/stac-extensions/eo) has all common names approved

**Comment by m-mohr** [comment]
We have a new proposal up: https://github.com/stac-extensions/eo/pull/22

**Comment by davemlz** [comment]
Mapping updated! ;) Thanks @m-mohr!

**Comment by m-mohr** [comment]
@davemlz Just want to let you know that we finally released the (I hope) ASI-compatible common band names in STAC: https://github.com/stac-extensions/eo?tab=readme-ov-file#common-band-names (available in v2.0.0)

**Comment by davemlz** [comment]
That's perfect! Thank you @m-mohr!
