### ISSUE TITLE
Potential error in NDSo(i)I

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [awesome-spectral-indices/awesome-spectral-indices#45]
The spectral index `NDSoI` has two different spellings: the entry in the JSON reads `NDSoI` but the `short_name` is given as `NDSoiI` creating some problems in workflows over at SpectralIndices.jl. Is this correct or is it a small typo? If so, which is the correct one?

**Comment by MartinuzziFrancesco** [comment]
I'm sorry for the label, it was added in automatic. This is, in fact, not a new index

**Comment by davemlz** [comment]
Done! ;)

**Comment by MartinuzziFrancesco** [comment]
you are the best mate, thanks
