### ISSUE TITLE
Question about application domain and equation parameters

### ISSUE THREAD

**Issue by EmanuelCastanho** [awesome-spectral-indices/awesome-spectral-indices#50]
Hi,

I want to contribute with spectral indexes that are used to detect features at the surface of the ocean: oil spills (OSI), floating vegetation (FAI), floating debris (FDI, PI), ... Should I include these in the water domain? Should Floating Algae Index (FAI) be included in the vegetation domain, although it is applied on the ocean?

Also, FAI and FDI (Floating Debris Index) depend on the NIR and Red Edge 2 wavelengths that change between Sentinel-2A and Sentinel-2B. I see that lambdaN is already defined, but not lambdaRE2, does these parameters take into consideration Sentinel-2 A and B different values?

**Comment by davemlz** [comment]
Hi @EmanuelCastanho!

I would say that as long as they are applied to water bodies you include them in the water domain ;) so, yes, you can put all of them in this category.

Regarding the lambdaRE2, it would be a user-defined parameter, so you can actually select the values you need (either S2A or S2B) when computing the index. Just remember to add the `lambdaRE2` parameter here if you are submitting a PR: https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/main/src/constants.py. If you are submitting an issue I will add it ;)

Cheers!

David
