### ISSUE TITLE
NBAI is wrong

### ISSUE THREAD

**Issue by RaphaelDELAIR** [awesome-spectral-indices/awesome-spectral-indices#51]
Hi,

I was doing some correlation analysis when I found out that NBAI was the exact opposite of NSDS which is not the case in the original paper. There is an error in NBAI formulation in your CSV file.

You defined it like this : ((S2 - S1)/G)/((S2 + S1)/G)

But the original paper formulated it like this :
NBAI = (TM7 – TM5/TM2)/ (TM7 + TM5/TM2)

You put extra parenthesis before dividing by the green band.

Hope this correction can help others not to make any mistakes.

(also FYI some indices are redundant : 
NDBI = - NDMI
NDWI = VgNIRBI
VrNIRBI = - NDVI
)

Thanks for this gathering of spectral indices though, it helps to know what exists in the litterature !

**Comment by davemlz** [comment]
Hey @RaphaelDELAIR!

You are right, I will correct the NBAI index now! Thank you for spotting it!

Regarding the redundant indices: That's fine, there are a lot. The idea of the catalogue is to have them all with their respective reference, even if duplicated or redundant.

Cheers!

**Comment by davemlz** [comment]
Index corrected! Thank you very much again!

Cheers!

David
