### ISSUE TITLE
message: "Token is required" for DOI of Shadow Index

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [awesome-spectral-indices/awesome-spectral-indices#53]
SI: Shadow Index
* Application Domain: vegetation
* Bands/Parameters: Any["B", "G", "R"]
* Formula: ((1.0-B)*(1.0-G)*(1.0-R))^(1/3)
* Reference: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.465.8749&rep=rep1&type=pdf

The reference returns `message: "Token is required"`

**Comment by davemlz** [comment]
I know. I have an Issue open on this already </3

Closing as duplicated.
