### ISSUE TITLE
sNIRvNDVILSWIS and sNIRvNDVILSWIP have the same `short_name` sNIRvNDVIxLSWI

### ISSUE THREAD

**Issue by MartinuzziFrancesco** [awesome-spectral-indices/awesome-spectral-indices#56]
Pretty much title, this is messing up the downstream function creation over at SpectralIndices.jl

**Comment by davemlz** [comment]
Very title, much wow: such corrected: https://github.com/awesome-spectral-indices/awesome-spectral-indices/commit/23dae80a84f0e564a5cce94b175af6bd0e68dffc (sorry!)

**Comment by MartinuzziFrancesco** [comment]
thanks man <3
