### ISSUE TITLE
NEW INDEX: CRI2 (Detects leaf carotenoid content)

### ISSUE THREAD

**Issue by eomasters-repos** [awesome-spectral-indices/awesome-spectral-indices#60]
I found the following index and I think it should be included.

```python
CRI2=SpectralIndex(
    short_name='CRI2',
    long_name='Detects leaf carotenoid content',
    formula='(1 / B) - (1 / RE1)',
    reference='https://doi.org/10.1562/0031-8655(2002)0750272ACCIPL2.0.CO2r',
    application_domain='vegetation',
    date_of_addition='2024-07-23',
    contributor="https://github.com/eomasters-repos"
)

**Comment by davemlz** [comment]
Dear @eomasters-repos,

Thank you very much for the contribution!

Some notes before proceeding:

1. The DOI doesn't work, so the index reference and formula can't be checked.
2. The long name should be the name of the index and not the description or goal of it. E.g. the long name of the NDVI is Normalized Difference Vegetation Index.

Please update the index to continue with the process.

Cheers!

David

**Comment by eomasters-repos** [comment]
Oh sorry, fixed the DOI link and the long_name.

CRI2=SpectralIndex(
    short_name='CRI2',
    long_name='Carotenoid Reflectance Index 2',
    formula='(1 / B) - (1 / RE1)',
    reference='https://doi.org/10.1562/0031-8655(2002)0750272ACCIPL2.0.CO2',
    application_domain='vegetation',
    date_of_addition='2024-07-23',
    contributor="https://github.com/eomasters-repos"
)

Also mentioned here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9268975

Ciao
Marco

**Comment by davemlz** [comment]
Thank you very much!

The index has been added with the original name CRI700, presented by the paper.

Cheers!
