### ISSUE TITLE
Landsat 8, B5: NIR08 instead of NIR?

### ISSUE THREAD

**Issue by m-mohr** [awesome-spectral-indices/awesome-spectral-indices#62]
Looking at the wavelength and bandwith, isn't Landsat 8, B5 more a NIR08 band rather than a NIR band?
It is much more similar to S2 B8A which is also in NIR08...

See also https://eoreader.readthedocs.io/en/v0.19.1/optical_band_mapping.html, which visualizes it quite nicely.

**Comment by davemlz** [comment]
While true, I think putting B8A from S2 and B5 from L8 is not quite ok, the bandwith of B8A is too narrow.

**Comment by davemlz** [comment]
Ahh wait. You are totally right. I was confusing everything!

**Comment by davemlz** [comment]
Done! Thank you @m-mohr!
