### ISSUE TITLE
Missing default values?

### ISSUE THREAD

**Issue by LaurentBerder** [awesome-spectral-indices/awesome-spectral-indices#63]
Hi,

I notice that some indices do not function (e.g. FAI, NDGI) because of the missing default values for lambda constants (`lambdaR`, `lambdaG`...)

https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/23dae80a84f0e564a5cce94b175af6bd0e68dffc/src/constants.py#L58-L77

Is it normal that these constants are defaulted to `None`?

**Comment by davemlz** [comment]
Hey Laurent!

Yes, their default is None as you should select the central wavelength according to your sensor.

The default values for different sensors are included in `spyndex` and can be easily retrieved (please check https://spyndex.readthedocs.io/en/latest/stubs/spyndex.axioms.PlatformBand.html#spyndex.axioms.PlatformBand). SO, if you want to compute e.g. NDGI for Sentinel-2A, you can just do:

```python
NDGI = spyndex.computeIndex(
    "NDGI",
    G = your_green_data,
    N = your_NIR_data,
    R = your_red_data,
    lambdaG = spyndex.bands.G.sentinel2a.wavelength,
    lambdaN = spyndex.bands.N.sentinel2a.wavelength,
    lambdaR = spyndex.bands.R.sentinel2a.wavelength
)
``` 

You can check the available sensors (well, in this case platforms) here: https://spyndex.readthedocs.io/en/latest/stubs/spyndex.axioms.Band.html#spyndex.axioms.Band

If your sensor is not listed, then you have to add the values by yourself ;)

I hope this helps!

David

**Comment by LaurentBerder** [comment]
Thanks @davemlz, what a quick response!

So if I understand what you're saying, these are `band` wavelengths, not `constant` values, right?
I was confused, since they're defined in the [constants](https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/23dae80a84f0e564a5cce94b175af6bd0e68dffc/src/constants.py) file, not in the [bands](https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/23dae80a84f0e564a5cce94b175af6bd0e68dffc/src/bands.py) one
