### ISSUE TITLE
NEW INDEX: NDPI

### ISSUE THREAD

**Issue by CvenGeo** [awesome-spectral-indices/awesome-spectral-indices#9]
```python
NDPI=SpectralIndex(
    short_name='NDPI',
    long_name='Normalized Difference Pond Index',
    formula='(S1- G) / (S1 + G)',
    reference='https://doi.org/10.1016/j.rse.2006.07.012',
    type='water',
    date_of_addition='2022-09-29',
    contributor="https://github.com/CvenGeo"
)
```

**Comment by davemlz** [comment]
Hi @CvenGeo!

I revised your index suggestion and it was perfectly aligned with the Awesome Spectral Indices (ASI) standard!

Please note that the index identifier was changed to `NDPonI` to avoid conflicts with the Normalized Difference Phenology Index (`NDPI`) and the Normalized Difference Polarization Index (`NDPolI`).

The index was added to the catalogue and it will be available in the next version of ASI.

Thank you very much for all your contributions to the catalogue!

Cheers!
